//! Order service module — CQRS + Event Sourcing best practices
//!
//! Shows:
//! - Typed mediator with zero-allocation dispatch
//! - CQRS: Commands vs Queries vs Events
//! - Compensating flows for transactional consistency
//! - Event sourcing: recording and projecting events

pub mod domain;
pub mod service;

pub use domain::*;
pub use service::OrderService;

// Re-export the typed mediator generated by #[catga_service]
pub use service::OrderMediator;
