[package]
name = "catga-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
streams-rpc = []

[dependencies]
async-trait = { workspace = true }
catga-core = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = "0.4"
redis = { version = "1", features = ["connection-manager", "tokio-comp"] }
serde = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tokio-util = { workspace = true, features = ["rt"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
criterion = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread", "time"] }

[[bench]]
name = "redis_throughput"
harness = false
