[package]
name = "catga-macros"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }

[dev-dependencies]
async-trait = "0.1"
catga-core = { path = "../catga-core" }
trybuild = "1.0"
