[workspace]
members = [
    "crates/catga-core",
    "crates/catga-macros",
    "crates/catga-memory",
    "tests",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT"
repository = "https://github.com/Cricle/Catga"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
