//! Demo of dynamic documentation generated by #[catga_service]
//!
//! Hover over `registry()` to see the auto-generated docs listing all handlers.
//! The docs show handlers grouped by type: Requests, Commands, Events.

use catga_core::{catga_command, catga_event, catga_request, catga_service, CatgaResult};

// Command type
#[derive(catga_command)]
struct Log(String);

// Request type (with response)
#[catga_request(response = String)]
struct Ping(String);

// Event type
#[derive(catga_event, Clone)]
struct OrderPlaced {
    #[allow(dead_code)]
    order_id: u64,
}

#[derive(Clone)]
struct Calculator;

// This service has all three handler types: Request, Command, Event
#[catga_service]
impl Calculator {
    /// Handles ping requests and returns a greeting
    async fn ping(&self, msg: Ping) -> CatgaResult<String> {
        Ok(format!("pong: {}", msg.0))
    }

    /// Logs a message (command, no response)
    async fn log(&self, cmd: Log) -> CatgaResult<()> {
        println!("LOG: {}", cmd.0);
        Ok(())
    }

    /// Handles order placed events
    async fn on_order_placed(&self, _event: OrderPlaced) -> CatgaResult<()> {
        Ok(())
    }
}

#[tokio::main]
async fn main() -> CatgaResult<()> {
    let calc = Calculator;

    // Hover over registry() to see dynamic docs listing all handlers
    let _registry = calc.registry()?;
    println!("Registry created successfully");

    println!("All tests passed!");
    Ok(())
}
