[package]
name = "catga-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
arc-swap = "1"
async-trait = "0.1"
base64 = "0.22"
brotli = "8"
catga-macros = { path = "../catga-macros" }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
futures = "0.3"
hmac = "0.12"
sha2 = "0.10"
tokio = { version = "1", features = ["rt", "time"] }
