//! Order messages and the HTTP response model.

use serde::{Deserialize, Serialize};

use catga_core::{Command, Event, Message, Request};

#[derive(Deserialize)]
pub(crate) struct PlaceOrder {
    pub(crate) quantity: u32,
    pub(crate) unit_price_cents: u64,
}

impl Message for PlaceOrder {}

impl Request for PlaceOrder {
    type Response = OrderAccepted;
    type TypeId = catga_core::DefaultMessageTypeId;
}

#[derive(Clone)]
pub(crate) struct RecordOrder {
    pub(crate) order_id: Box<str>,
    pub(crate) quantity: u32,
    pub(crate) total_cents: u64,
}

impl Message for RecordOrder {}
impl Command for RecordOrder { type TypeId = catga_core::DefaultMessageTypeId; }

#[derive(Clone)]
pub(crate) struct GetOrder {
    pub(crate) order_id: Box<str>,
}

impl Message for GetOrder {}

impl Request for GetOrder {
    type Response = OrderAccepted;
    type TypeId = catga_core::DefaultMessageTypeId;
}

#[derive(Clone, Serialize, Deserialize)]
pub(crate) struct OrderCompleted {
    pub(crate) order_id: Box<str>,
    pub(crate) total_cents: u64,
}

impl Message for OrderCompleted {}
impl Event for OrderCompleted { type TypeId = catga_core::DefaultMessageTypeId; }

/// The HTTP and CQRS response returned when an order has completed checkout.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct OrderAccepted {
    /// The stable order identifier generated by the command handler.
    pub order_id: Box<str>,
    /// The validated quantity submitted to checkout.
    pub quantity: u32,
    /// The checked price total in cents.
    pub total_cents: u64,
}
