[package]
name = "catga-robustmq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
catga-codec-memorypack = { workspace = true }
catga-core = { workspace = true }
robustmq = "1"
serde = "1"
tokio = { version = "1", features = ["sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "time"] }
