//! Demonstrates the zero-allocation typed mediator generated by `#[catga_service(MyMediator)]`.
//!
//! Unlike the dynamic `Mediator` (which uses type-erased dispatch through `Box<dyn Any>`),
//! the typed mediator stores handlers as concrete struct fields and dispatches through
//! compiler-monomorphized sealed traits — no heap allocation, no downcast, no vtable.

use catga_core::{CatgaResult, catga_command, catga_event, catga_request, catga_service};

#[catga_request(response = u64)]
struct GetBalance {
    account_id: u64,
}

#[derive(catga_command)]
struct TransferFunds {
    from: u64,
    to: u64,
    amount: u64,
}

#[derive(catga_event, Clone)]
struct TransferCompleted {
    from: u64,
    to: u64,
    amount: u64,
}

// ---------------------------------------------------------------------------
// Service with typed mediator — zero-allocation dispatch
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct BankService;

#[catga_service(BankMediator)]
impl BankService {
    async fn get_balance(&self, msg: GetBalance) -> CatgaResult<u64> {
        Ok(msg.account_id * 1000)
    }

    async fn transfer(&self, cmd: TransferFunds) -> CatgaResult<()> {
        println!(
            "  transferred {} from account {} to account {}",
            cmd.amount, cmd.from, cmd.to
        );
        Ok(())
    }

    async fn on_transfer_completed(&self, event: TransferCompleted) -> CatgaResult<()> {
        println!(
            "  [audit] transfer of {} from {} to {}",
            event.amount, event.from, event.to
        );
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main(flavor = "current_thread")]
async fn main() -> CatgaResult<()> {
    let service = BankService;
    let mediator = BankMediator::new(service);

    // Typed request dispatch — compiler monomorphizes, zero Box allocation.
    let balance = mediator.send(GetBalance { account_id: 42 }).await?;
    println!("account 42 balance: {balance}");
    assert_eq!(balance, 42_000);

    // Typed command dispatch.
    mediator
        .send_command(TransferFunds {
            from: 42,
            to: 99,
            amount: 500,
        })
        .await?;

    // Typed event publish.
    mediator
        .publish(TransferCompleted {
            from: 42,
            to: 99,
            amount: 500,
        })
        .await?;

    println!("typed mediator: all dispatches completed with zero heap allocation");
    Ok(())
}
