//! Demonstrates the zero-allocation typed mediator generated by `catga_typed_mediator!`.
//!
//! Unlike the dynamic `Mediator` (which uses type-erased dispatch through `Box<dyn Any>`),
//! the typed mediator stores handlers as concrete struct fields and dispatches through
//! compiler-monomorphized sealed traits — no heap allocation, no downcast, no vtable.

use async_trait::async_trait;
use catga_core::{
    CatgaResult, Command, CommandHandler, Event, EventHandler, Handler, Message, Request,
    catga_typed_mediator,
};

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

struct GetBalance {
    account_id: u64,
}
impl Message for GetBalance {}
impl Request for GetBalance {
    type Response = u64;
}

#[derive(Clone)]
struct TransferFunds {
    from: u64,
    to: u64,
    amount: u64,
}
impl Message for TransferFunds {}
impl Command for TransferFunds {}

#[derive(Clone)]
struct TransferCompleted {
    from: u64,
    to: u64,
    amount: u64,
}
impl Message for TransferCompleted {}
impl Event for TransferCompleted {}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

struct BalanceHandler;

#[async_trait]
impl Handler<GetBalance> for BalanceHandler {
    async fn handle(&self, query: GetBalance) -> CatgaResult<u64> {
        // Simulated balance lookup.
        Ok(query.account_id * 1000)
    }
}

struct TransferHandler;

#[async_trait]
impl CommandHandler<TransferFunds> for TransferHandler {
    async fn handle(&self, cmd: TransferFunds) -> CatgaResult<()> {
        println!(
            "  transferred {} from account {} to account {}",
            cmd.amount, cmd.from, cmd.to
        );
        Ok(())
    }
}

#[derive(Clone)]
struct AuditLogger;

#[async_trait]
impl EventHandler<TransferCompleted> for AuditLogger {
    async fn handle(&self, event: TransferCompleted) -> CatgaResult<()> {
        println!(
            "  [audit] transfer of {} from {} to {}",
            event.amount, event.from, event.to
        );
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Typed mediator — zero-allocation dispatch
// ---------------------------------------------------------------------------

catga_typed_mediator! {
    pub struct BankMediator;
    request GetBalance => BalanceHandler;
    command TransferFunds => TransferHandler;
    event TransferCompleted => [AuditLogger];
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main(flavor = "current_thread")]
async fn main() -> CatgaResult<()> {
    let mediator = BankMediator::new(BalanceHandler, TransferHandler, [AuditLogger]);

    // Typed request dispatch — compiler monomorphizes, zero Box allocation.
    let balance = mediator.send(GetBalance { account_id: 42 }).await?;
    println!("account 42 balance: {balance}");
    assert_eq!(balance, 42_000);

    // Typed command dispatch.
    mediator
        .send_command(TransferFunds {
            from: 42,
            to: 99,
            amount: 500,
        })
        .await?;

    // Typed event publish — fan-out to all registered handlers.
    mediator
        .publish(TransferCompleted {
            from: 42,
            to: 99,
            amount: 500,
        })
        .await?;

    println!("typed mediator: all dispatches completed with zero heap allocation");
    Ok(())
}
