[package]
name = "catga-cluster"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
arc-swap = "1"
async-trait = "0.1"
catga-core = { path = "../catga-core" }
metrics = "0.24"
parking_lot = "0.12"
raft = { version = "0.7", default-features = false, features = ["protobuf-codec"] }
raft-engine = { version = "0.4", default-features = false }
serde = { version = "1", features = ["derive"] }
slog = "2"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"
