[package]
name = "catga-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
catga-core = { workspace = true }
catga-flow = { workspace = true }
catga-memory = { workspace = true }
dashmap = "6"
futures = "0.3"
