[package]
name = "memorypack-benchmark"
version = "0.0.1"
edition = "2024"
publish = false

[workspace]

[features]
dhat-heap = ["dhat"]

[dependencies]
catga-codec-memorypack = { path = "..", features = ["ahash"] }
dhat = { version = "0.3", optional = true }
ahash = "0.8"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "memorypack_bench"
harness = false
