[package]
name = "catga-codec-bincode"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
bincode-next = { version = "3.1.1", default-features = false, features = ["alloc", "derive"] }
catga-core = { path = "../catga-core", version = "0.0.1" }
